spring.cloud.stream:
  function:
    definition: monitorConsumer
  bindings:
    monitorConsumer-in-0:
      destination: monitor
spring:
    kafka:
        bootstrap-servers:
          - localhost:29092
        binder:
            brokers:
              - localhost:29092